#define GET_VM_AREA	(void *)0xffffffffade7edf0
#define ZAP_PAGE_RANGE	(void *)0xffffffffade64910
#define MAP_KERNEL_RANGE_NOFLUSH	(void *)0xffffffffade7c170
#define UNMAP_KERNEL_RANGE	(void *)0xffffffffade7c550
#define GET_FILES_STRUCT	(void *)0xffffffffadf07c20
#define PUT_FILES_STRUCT	(void *)0xffffffffadf07c60
#define __LOCK_TASK_SIGHAND	(void *)0xffffffffadcb1c00
#define __ALLOC_FD	(void *)0xffffffffadf07de0
#define __FD_INSTALL	(void *)0xffffffffadf07f90
#define __CLOSE_FD	(void *)0xffffffffadf07050
#define CAN_NICE	(void *)0xffffffffadcd3010
#define SECURITY_BINDER_SET_CONTEXT_MGR	(void *)0xffffffffae05f250
#define SECURITY_BINDER_TRANSACTION	(void *)0xffffffffae05f290
#define SECURITY_BINDER_TRANSFER_BINDER	(void *)0xffffffffae05f2e0
#define SECURITY_BINDER_TRANSFER_FILE	(void *)0xffffffffae05f330
